[package]
name = "tokenizers"
# Bump minor.patch version every time we bump tokenizers dependency version.
# Can't bump major version because Go doesn't like major version >= 2.
version = "1.22.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.162"
tokenizers = {version = "0.20.2" }
tiktoken-rs = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
base64 = "0.22"
rustc-hash = "1.1.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"

[[bench]]
name = "decode_benchmark"
harness = false
